name: "Pull Request Docs Check"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: make folder
      run: |
        mkdir /tmp/sphinx-log
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"